config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :orders
    resources :products do
      resources :stocks
    end
    resources :categories
  end
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  authenticated :admin_user do
    root to: "admin#index", as: :admin_root
  end

  resources :categories, only: [:show]
  resources :products, only: [:show]

  get "admin" => "admin#index"
  get "category" => "categories#index"
  get "cart" => "carts#show"
  post "checkout" => "checkouts#create"
  get "success" => "checkouts#success"
  get "cancel" => "checkouts#cancel"
  post "webhooks" => "webhooks#stripe"

end

app/models/product.rb
class Product < ApplicationRecord
  has_many_attached :images do |attachable|
    attachable.variant :thumb, resize_to_limit: [50, 50]
    attachable.variant :medium, resize_to_limit: [250, 250]

  end
  belongs_to :category
  has_many :stocks
  has_many :order_products
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  before_action :set_admin_product, only: %i[ show edit update destroy ]

  # GET /admin/products or /admin/products.json
  def index
    if params[:query].present?
      @pagy, @admin_products = pagy(Product.where("name LIKE ?", "%#{params[:query]}%"))
    else
      @pagy, @admin_products = pagy(Product.all)
    end
  end

  # GET /admin/products/1 or /admin/products/1.json
  def show
  end

  # GET /admin/products/new
  def new
    @admin_product = Product.new
  end

  # GET /admin/products/1/edit
  def edit
  end

  # POST /admin/products or /admin/products.json
  def create
    @admin_product = Product.new(admin_product_params)

    respond_to do |format|
      if @admin_product.save
        format.html { redirect_to admin_product_url(@admin_product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @admin_product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/products/1 or /admin/products/1.json
  def update
    if @admin_product.update(admin_product_params.reject{ |k| k["images"] })
      if admin_product_params["images"]
        admin_product_params["images"].each do |image|
          @admin_product.images.attach(image)
        end
      end
      redirect_to admin_products_path, notice: "Product Successfully Updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /admin/products/1 or /admin/products/1.json
  def destroy
    @admin_product.destroy

    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_product
      @admin_product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_product_params
      params.require(:product).permit(:name, :description, :price, :category_id, :active, images: [])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_with(model: [:admin, admin_product]) do |form| %>
  <% if admin_product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(admin_product.errors.count, "error") %> prohibited this admin_product from being saved:</h2>

      <ul>
        <% admin_product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.collection_select :category_id, Category.order(:name), :id, :name %>
  </div>

  <div>
    <%= form.label :active, style: "display: block" %>
    <%= form.check_box :active %>
  </div>

  <div>
    
    <% if admin_product.images.any? %>
      <% admin_product.images.each do |image| %>
        <%= image_tag image, class:"w-20 h-20 object-cover rounded-md" %>
      
      <% end %>
      
      
    <% end %>
    
    <%= form.label :images, style: "display: block" %>
    <%= form.file_field :images, multiple: true %>
  </div>

  <div class="my-5">
    <%= link_to "Product Stock", admin_product_stocks_path(admin_product), class:"underline" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= product.category_id %>
  </p>

  <p>
    <strong>Active:</strong>
    <%= product.active %>
  </p>

</div>

app/views/admin/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", admin_product: @admin_product %>

<br>

<div>
  <%= link_to "Show this product", [:admin, @admin_product] %> |
  <%= link_to "Back to products", admin_products_path %>
</div>

app/views/admin/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Products</h1>
<div class="flex mt-4 flex-col md:flex-row items-start md:items-center w-full">
  <%= form_with url: admin_products_path, method: :get, class:"flex" do |form| %>
    <%= form.text_field :query, placeholder: "Search", class:"rounded-lg border-gray-500 text-gray-800" %>
    <%= form.submit "Submit", class:"cursor-pointer bg-gray-500 ml-2 hover:bg-gray-600 text-white py-2 px-4 rounded" %>
  <% end %>
  <%= form_with url: admin_products_path, method: :get, class: 'flex' do |form| %>
    <%= form.submit "Clear", class: "cursor-pointer bg-gray-500 ml-0 md:ml-2 mt-2 md:mt-0 hover:bg-gray-600 text-white py-2 px-4 rounded" %>
  <% end %>
  
</div>

<div class="flex flex-col w-full">
  <div class="overflow-x-auto sm:mx-0.5 lg:mx-0.5">
    <div class="py-2 inline-block min-w-full">
      <div class="overflow-x-auto">
        <table class="min-w-full overflow-x-scroll">
          <thead class="bg-white border-b">
            <tr>
              <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left"> 
              </th>
              <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left"> 
                Name
              </th>
              <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left"> 
                Descrption
              </th>
              <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left"> 
                Price
              </th>
            </tr>
          </thead>

          <tbody>
            <% @admin_products.each do |p| %>
              <tr class="bg-gray-50 border-b">

                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800 underline">
                  <%= p.images.any? ? image_tag(p.images.first.variant(:thumb))  : image_tag("https://via.placeholder.com/50") %>
                </td>

                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800 underline">
                  <%= link_to p.name, edit_admin_product_path(p) %>
                </td>

                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800">
                  <%= p.description %>
                </td>

                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800">
                  $<%= (p.price / 100.0).to_s %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
      </div>
    </div>
  </div>
</div>

<%= link_to "New product", new_admin_product_path %>

app/views/admin/products/new.html.erb
<h1>New product</h1>

<%= render "form", admin_product: @admin_product %>

<br>

<div>
  <%= link_to "Back to products", admin_products_path %>
</div>

app/views/admin/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @admin_product %>

<div>
  <%= link_to "Edit this product", edit_admin_product_path(@admin_product) %> |
  <%= link_to "Back to products", admin_products_path %>

  <%= button_to "Destroy this product", [:admin, @admin_product], method: :delete %>
</div>